-- 1. Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  bio TEXT,
  favorite_movie_id INT,
  avatar_url TEXT,
  theme_preference TEXT DEFAULT 'light',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. Movie Logs Table
CREATE TABLE movie_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  tmdb_id INT NOT NULL,
  watched_date DATE,
  rating NUMERIC(2,1) CHECK (rating >= 0 AND rating <= 5), -- allows 0.5 steps
  notes TEXT,
  theater_name TEXT,
  poster_path TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. Follows Table
CREATE TABLE follows (
  follower_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  following_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
  PRIMARY KEY (follower_id, following_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE movie_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." 
ON profiles FOR SELECT TO public USING (true);

CREATE POLICY "Users can insert their own profile." 
ON profiles FOR INSERT TO public WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." 
ON profiles FOR UPDATE TO public USING (auth.uid() = id);

-- Movie Logs Policies
CREATE POLICY "Movie logs are viewable by everyone." 
ON movie_logs FOR SELECT TO public USING (true);

CREATE POLICY "Users can insert their own logs." 
ON movie_logs FOR INSERT TO public WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own logs." 
ON movie_logs FOR UPDATE TO public USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own logs." 
ON movie_logs FOR DELETE TO public USING (auth.uid() = user_id);

-- Follows Policies
CREATE POLICY "Follows are viewable by everyone" 
ON follows FOR SELECT TO public USING (true);

CREATE POLICY "Users can follow others" 
ON follows FOR INSERT TO public WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow others" 
ON follows FOR DELETE TO public USING (auth.uid() = follower_id);
